name: Dev Pull Request

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        timeout-minutes: 60
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
          # path: node_modules

      - name: Install
        run: npm ci

      - name: Test
        run: npm run lint # && npm run test

      - name: Build
        run: npm run build

  on-success:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: snow-actions/line-notify@v1.1.0
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: |
            The "Dev Pull Request" passed.
            ${{ github.event.pull_request.html_url }}

  on-failure:
    needs: build
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - uses: snow-actions/line-notify@v1.1.0
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: |
            The "Dev Pull Request" failed.
            ${{ github.event.pull_request.html_url }}
